# Generated by Django 4.0.2 on 2022-02-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textType', models.TextField(max_length=5000, null=True)),
                ('language', models.CharField(choices=[('English (United Kingdom)', 'English (United Kingdom)'), ('English (United States)', 'English (United States)'), ('German', 'German'), ('Hindi', 'Hindi')], max_length=50)),
            ],
        ),
    ]
