# Generated by Django 4.0.2 on 2022-02-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdfType', models.FileField(upload_to='pdfs')),
                ('language', models.CharField(choices=[('English (United Kingdom)', 'English (United Kingdom)'), ('English (United States)', 'English (United States)'), ('German', 'German'), ('Hindi', 'Hindi')], max_length=50)),
            ],
        ),
    ]
