# Generated by Django 4.0.2 on 2022-02-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_pdfform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfform',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('German', 'German'), ('Hindi', 'Hindi'), ('Marathi', 'Marathi')], max_length=50),
        ),
        migrations.AlterField(
            model_name='textform',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('German', 'German'), ('Hindi', 'Hindi'), ('Marathi', 'Marathi')], max_length=50),
        ),
    ]
