# Generated by Django 4.0.2 on 2022-02-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_videoform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textform',
            old_name='language',
            new_name='voices',
        ),
        migrations.AlterField(
            model_name='pdfform',
            name='language',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=50),
        ),
    ]
