# Generated by Django 4.0.2 on 2022-02-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0005_rename_language_textform_voices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfform',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('German', 'German'), ('Hindi', 'Hindi'), ('Marathi', 'Marathi')], max_length=50),
        ),
        migrations.AlterField(
            model_name='textform',
            name='voices',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=50),
        ),
    ]
